#!/bin/sh /etc/rc.common
USE_PROCD=1
START=94
STOP=94

start_service() {
    procd_open_instance
    procd_set_param command sh /usr/bin/link_monitor.sh
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
